/*import { clickTheButton, chooseColor, chooseRomance, chooseMusical, chooseMistakenId, chooseInn, chooseRoyal, chooseFamily, chooseCountry,
    chooseCorp, chooseWish, chooseSanta, chooseAdaptation, chooseFresh, choosePrecociousChild, chooseBaker, chooseDeadParent,
    chooseFamousActor, chooseChildStar, chooseFamilyFriendly, choosePilf, chooseMovie } from './moviechooser.js';*/


let XmasMovies = [
    {
        title: "A Bad Moms Christmas",
        myScore: 100,
        summary: "A trio of overwhelmed mom friends decide to take Christmas easy this year...until their needy moms come to town.",
        comments: "If you're looking to unwind and have a laugh on your own while you're wrapping presents or baking cookies, this movie is for you.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: true
    },
    {   title: "A California Christmas",
        myScore: 43,
        summary: "In order to win his mother's approval, a lawyer poses as a farm hand in order to coerce a struggling farmess into selling her land.",
        comments: "This one was really bad. Why is the 'feisty,', I-don't-need-to-be-rescued female 'protagonist' (less screen time than the male protagonist and his bro driver) constantly making excuses for the violent asshole friend of her late fiance who keeps pressuring her to go out with him? Also, the male protagonist looked too much like Martin Shkreli", 
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: false,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "A Christmas Carol",
        myScore: 73,
        summary: "A rich old man learns the meaning of Christmas from four ghosts.",
        comments: "Tied for fourth, pretty boring to watch as an adult. Fun fact: this was a made-for-TV movie, which is why it's not exactly the most dynamic thing ever.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "A Christmas Prince",
        myScore: 56,
        summary: "A journalist breaks into a foreign royal family's home and poses as a new employee so she can get the scoop on the heir's plans to take the throne...or not.",
        comments: "It's not good in the bad sort of way, or bad in the good sort of way. It's just bad in the bad sort of way.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false,
    },
    {   title: "A Christmas Prince: Royal Wedding",
        myScore: 54,
        summary: "A queen-to-be feels overwhelmed as royal protocols take over her hopes of a small wedding.",
        comments: "You\'re going to a be a queen, of course your life isn\'t your own, didn\'t you learn anything from Diana, you dumb bitch?",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "A Christmas Prince: The Royal Baby",
        myScore: 63,
        summary: "With her first child\'s arrival imminent, the queen has to solve the mystery of the missing artifact that maintains peace between neighboring countries.",
        comments: "I know that when Queen Elizabeth had an emergency, they used to send Prince Philip out alone on a horse in the snow. He probably would have preferred that, actually", 
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Die Hard",
        myScore: 95,
        summary: "A vacationing NYPD officer flies to L.A. to reconcile with his estranged wife, only to find her workplace Christmas party overrun by terrorists.",
        comments: "It's a perfect movie but it doesn't exactly get me into the Christmas spirit.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: true,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: true
    },
    {
        title: "Miracle on 34th Street",
        myScore: 100,
        summary: "A little girl discovers that Santa Claus is real after he works as a Santa Claus at her mother's department store.",
        comments: "A Christmas classic that will make anyone wish Santa were real.",
        inColor: false,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
]

    /*  title:
        myScore:
        summary:
        comments: 
        inColor: 
        romance: 
        musical: 
        mistakenIdentity: 
        charmingInn: 
        royalFairyTale: 
        familyIsNumber1: 
        countryVsCity: 
        corporateLemming: 
        wishFulfillment: 
        realSanta: 
        adaptation: 
        freshStart: 
        precociousChild: 
        charmingBaker: 
        deadParent: 
        famousActor: 
        childActor: 
        familyFriendly:
        pilf:
        */

