/*import { clickTheButton, chooseColor, chooseRomance, chooseMusical, chooseMistakenId, chooseInn, chooseRoyal, chooseFamily, chooseCountry,
    chooseCorp, chooseWish, chooseSanta, chooseAdaptation, chooseFresh, choosePrecociousChild, chooseBaker, chooseDeadParent,
    chooseFamousActor, chooseChildStar, chooseFamilyFriendly, choosePilf, chooseMovie } from './moviechooser.js';*/


let XmasMovies = [
    {
        title: "A Bad Moms Christmas",
        myScore: 100,
        summary: "A trio of overwhelmed mom friends decide to take Christmas easy this year...until their needy moms come to town.",
        comments: "If you're looking to unwind and have a laugh on your own while you're wrapping presents or baking cookies, this movie is for you.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: true
    },
    {   title: "A California Christmas",
        myScore: 43,
        summary: "In order to win his mother's approval, a lawyer poses as a farm hand in order to coerce a struggling farmess into selling her land.",
        comments: "This one was really bad. Why is the 'feisty,', I-don't-need-to-be-rescued female 'protagonist' (less screen time than the male protagonist and his bro driver) constantly making excuses for the violent asshole friend of her late fiance who keeps pressuring her to go out with him? Also, the male protagonist looked too much like Martin Shkreli", 
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: false,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "A Christmas Carol",
        myScore: 73,
        summary: "A rich old man learns the meaning of Christmas from four ghosts.",
        comments: "Tied for fourth, pretty boring to watch as an adult. Fun fact: this was a made-for-TV movie, which is why it's not exactly the most dynamic thing ever.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "A Christmas Prince",
        myScore: 56,
        summary: "A journalist breaks into a foreign royal family's home and poses as a new employee so she can get the scoop on the heir's plans to take the throne...or not.",
        comments: "It's not good in the bad sort of way, or bad in the good sort of way. It's just bad in the bad sort of way.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false,
    },
    {   title: "A Christmas Prince: Royal Wedding",
        myScore: 54,
        summary: "A queen-to-be feels overwhelmed as royal protocols take over her hopes of a small wedding.",
        comments: "You\'re going to a be a queen, of course your life isn\'t your own, didn\'t you learn anything from Diana, you dumb bitch?",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "A Christmas Prince: The Royal Baby",
        myScore: 63,
        summary: "With her first child\'s arrival imminent, the queen has to solve the mystery of the missing artifact that maintains peace between neighboring countries.",
        comments: "I know that when Queen Elizabeth had an emergency, they used to send Prince Philip out alone on a horse in the snow. He probably would have preferred that, actually", 
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },{
        title: "A Christmas Story",
        myScore: 100,
        summary: "A man recounts the Christmas that he asked his parents for an air rifle, beat up the school bully, and discovered that prizes are pieces of junk.",
        comments: "The TBS marathon is overkill but it is *very* entertaining",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "A Cinderella Story: Christmas Wish",
        myScore: 68,
        summary: "A department store elf works to launch her music career as her step-family gets in the way.",
        comments: "Not terrible",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: true,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "A Family Reunion Christmas",
        myScore: 82,
        summary: "A family faces multiple struggles as they get ready for Christmas.",
        comments: "Angels are real? But I was genuinely touched by it",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: true,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "A Very Harold and Kumar Christmas",
        myScore: 74,
        summary: "Two stoners have to replace a Christmas tree they destroyed, but shenanigans stand in their way.",
        comments: "The sexual coercion scene was genuinely upsetting, but the rest was pretty funny",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: true
    },
    {
        title: "A Wish for Christmas",
        myScore: 75,
        summary: "A young woman fed up with being walked all over at work is given the chance to change her life when a magical Santa gives her 48 hours to be assertive.",
        comments: "I've watched this one every year. Don't @ me",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Alien Xmas",
        myScore: 85,
        summary: "An alien learns the true meaning of Christmas when he comes to Earth and is mistaken for a child's toy.",
        comments: "It was cute but frankly I wasn't really paying attention",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Angels in the Snow",
        myScore: 50,
        summary: "A bickering, privileged family stranded in a snowstorm provides a warm home to a less fortunate family stranded in the snowstorm.",
        comments: "They were dead the whole time. The movie title 'ruins' it, if there was anything to be ruined. Also, the Black familiy serves as a vehicle to teach them, instead of having their own character development.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Check Inn to Christmas",
        myScore: 79,
        summary: "Two former high school sweethearts convince their dads - who are lifelong business rivals - to cooperate and run a soulless corporation out of town.",
        comments: "Christmas trivia doesn't sound like anything you need to study for. The chemistry between the two leads - and the plot device that they'd known each other for decades - made a huge difference.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly:true,
        pilf: false
    },
    {
        title: "Christmas Every Day",
        myScore: 57,
        summary: "After his sister wishes for Christmas every day, a young teen's Christmas becomes increasingly frustrating.",
        comments: "I saw this when I was about 12. But only once. I didn't watch it nearly as many times as I watched that one with Mimi Rogers", 
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Christmas in Connecticut",
        myScore: 100,
        summary: "A popular lifestyle writer agrees to marry a stuffy Connecticut architect if he'll help her entertain her boss and a war hero for Christmas.",
        comments: "100% perfection, and Dennis Morgen and Barbara Stanwyck are both dreamboats",
        inColor: false,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Christmas Made to Order",
        myScore: 71,
        summary: "A struggling event planner helps a too-busy corporate man entertain his visiting family over the holidays.",
        comments: "the PILF sneaks in a Chevy Chase impression, which is a highlight",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Christmas Vacation",
        myScore: 100,
        summary: "A dedicated family man plans to give his family the perfect Christmas, but gets more family than he bargained for.",
        comments: "One of the few movies that truly captures how stressful and wonderful Christmas is. Bingo",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Christmas Wedding Planner",
        myScore: 34,
        summary: "A wedding plans finds her job interrupted when a private investigator looks into the groom's background.",
        comments: "omg I hate this one so much",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Christmas with a View",
        myScore: 51,
        summary: "A failed restauranteer working as a hostess at a luxury inn finds herself flustered when a reality show chef is hired for the holiday season.",
        comments: "There's actually banging in this one, which is rare",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: true,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Christmas with the Kranks",
        myScore: 78,
        summary: "After their daughter decides to travel for Christmas, her mom and dad choose to skip the holiday and go on a tropical vacation.",
        comments: "I love how horny they are for each other.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: true
    },   
    {
        title: "Christmas Wonderland",
        myScore: 76,
        summary: "A put-upon gallery assistant redisocvers her love of painting when she returns home to babysit her niblings...and she rediscovers her high school boyfriend, too.",
        comments: "I didn't hate it. I have a soft spot for Emily Osment. Apparently she spent four months shadowing at an art gallery to 'prepare' for the role. Overkill? Or being a good actor?",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: true,
        familyFriendly: true,
        pilf: true
    }, 
    {
        title: "Die Hard",
        myScore: 95,
        summary: "A vacationing NYPD officer flies to L.A. to reconcile with his estranged wife, only to find her workplace Christmas party overrun by terrorists.",
        comments: "It's a perfect movie but it doesn't exactly get me into the Christmas spirit.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: true,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: true
    },
    {
        title: "Dolly Parton's Christmas on the Square",
        myScore: 69,
        summary: "The residents of a small town come together to change the heart of its least jolly and richest resident, with the help of an angel and her trainee.",
        comments: "Without Dolly, it'd be pure garbage. A lot of problems with the theology - for example, that angels are magical enough to fix problems as complicated as fertility with one little finger twitch, but they choose not to. Also, Regina's dad was a piece of shit. Not just because he was so overprotective that she wasn't socialized properly and ended up getting pregnant as a teen, not just because he ripped that baby off her chest the second after he was born, but also because he was the richest man in town and ARPAB.",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: true,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "El Camino Christmas",
        myScore: 52,
        summary: "When a gas station robbery goes bad, the robbers, the cops, and the hostages have to decide what to do next.",
        comments: "SO depressing and mismarketed. It has a great cast and great acting, and the trailer makes it look like a romp, but there's very little comic relief.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Elf",
        myScore: 87,
        summary: "A failing publisher discovers that he has a grown son he never knew about...a son who was raised by elves at the North Pole.",
        comments: "I saw this movie in theaters four times, and I have no regrets. You might think I would be cynical about such beloved movie, but the fact is, it's very good, and it began the era of production companies trusting Jon Favreau.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: true,
        precociousChild: false,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Four Christmases",
        myScore: 78,
        summary: "A couple with divorced parents is forced to spend time with all four of their extended families after their self-serving vacation plans are exposed.",
        comments: "I was skeptical when it first came out, but seeing it a decade later, it's a classic. Incredible casting.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Happy Merry Whatever",
        myScore: 75,
        summary: "A man hoping to propose to his girlfriend over the holidays undergoes scrunity from her widowed, overprotective, ex-cop father when he joins her for the Christmas holiday.",
        comments: "The sitcomization of it brings its quality down a bit, but it's a solid sitcom. The well-worn concept is given new life by excellent performances and actual comedy.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Holidate",
        myScore: 85,
        summary: "Acquaintances agree to be each other's holiday dates for a year to avoid questions from their family and from any potential dates who might take things too seriously.",
        comments: "Genuinely funny and enjoyable. An actual movie.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: true
    },
    {
        title: "Holiday Home Makeover",
        myScore: 73,
        summary: "An interior designer who calls himself 'Mr. Christmas' helps families redo their homes for a special holiday.",
        comments: "I enjoyed it, but that one mom from Long Island was despicable.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Holiday in Handcuffs",
        myScore: 55,
        summary: "Freshly dumped and knowing her family is expecting to meet a boyfriend over the holidays, a desperate woman kidnaps a man she's just met who happens to be engaged to someone else.",
        comments: "This one was painful. I know Melissa Joan Hart and Mario Lopez have been out saving the galaxy since my grandfather was in diapers, but yeesh.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Holiday in the Wild",
        myScore: 46,
        summary: "A divorcee in her second act travels to Africa to volunteer at an elephant sanctuary.",
        comments: "White saviors and Kristen Davis? Barf. One of those white liberal embarrassments that Republicans point to at CPAC.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: true,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Holiday Inn",
        myScore: 90,
        summary: "A burnt-out entertainer opens an inn in Connecticut that will only be open on holidays.",
        comments: "I love this movie but the minstrel routine has to get a hard 0 in Audience.",
        inColor: false,
        romance: true,
        musical: true,
        mistakenIdentity: false, 
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: true,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Holiday Rush",
        myScore: 72,
        summary: "An unemployed radio DJ moves back into his childhood home after losing all his money.",
        comments: "Not bad!",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: true,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Home Alone",
        myScore: 79,
        summary: "A young boy is left home alone to the evil designs of a pair of crooks after his entire extended family misplaces him on their vacation to Paris.",
        comments: "I remember seeing this as a child at West Point and thinking that Kevin was a kid I wouldn't want to sit next to in class.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "How Sarah Got Her Wings",
        myScore: 43,
        summary: "A woman dies and as a final task before becoming a 'real' angel, has to help a man figure out how to love again.",
        comments: "This is one of those movies that I really just didn't understand. Did a person write this or is this one of those movies written by a Twitter bot?",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "I'll Be Home For Christmas",
        myScore: 48,
        summary: "A single mother learns to trust her estranged father when he passes through town before Christmas.",
        comments: "Boring and forgettable.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "It's a Wonderful Life",
        myScore: 100,
        summary: "A bankrupt banker is convinced not to take his own life by a bumbling angel-to-be.",
        comments: "I have sobbed while describing the plot of this movie.",
        inColor: false,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Jingle All the Way",
        myScore: 61,
        summary: "An eager-to-please dad fights shoppers of all shapes and sizes to get the hottest action figure for his son for Christmas.",
        comments: "This man successfully won political office in California.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Jingle Jangle: A Christmas Journey",
        myScore: 86,
        summary: "A once-great toymaker reconnects with his exucberant granddaughter and rediscovers his joy for life when he finds a magical toy in his workshop.",
        comments: "I have a lot of feelings about this one. There are parts I absolutely loved: Forest Whitaker, the actor who played Idi Amin, in a dance-off. Keegan-Michael Key doing anything. This movie bleeds Christmas. But, what's up with Buddy's powers? He doesn't seem to have any limitations or rules. The 'reveal' at the end is really weak, unless those children have never left their playroom before. Still, a fantastic romp.",
        inColor: true,
        romance: false,
        musical: true,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Let It Snow",
        myScore: 77,
        summary: "A group of teens in a snowed-in small town struggle to find themselves as Christmas descends.",
        comments: "I just want Liv Hewson to be able to play a non-binary character. There were some bits I really liked, and some bits that were really mediocre. Why do so many moms have vague cancer? The Mick Jagger dancing scene was unbearable.", 
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Love Actually",
        myScore: 68,
        summary: "Family members' and strangers' lives intersect in the month leading up to Christmas.",
        comments: "I used to love this movie and now I HATE IT.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: true,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Meet Me In St. Louis",
        myScore: 100,
        summary: "A young woman coming of age at the turn of the century falls in love with the boy next door.",
        comments: "I always cry at the Merry Little Christmas scene. Plus, knowing what Judy's life was like, you can't help but get verklempt.",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Merry Kissmas",
        myScore: 32,
        summary: "A woman with a self-centered fiance shares a magical kiss with a handsome stranger, and spends the rest of the day looking for him.",
        comments: "Doris Roberts is a sexual predator in this and it's not funny and it's not ok.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Mickey's Christmas Carol",
        myScore: 77,
        summary: "A rich old duck learns the meaning of Christmas from other Disney characters.",
        comments: "The third-best adaptation, and a tight 26 minutes.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Miracle on 34th Street",
        myScore: 100,
        summary: "A little girl discovers that Santa Claus is real after he works as a Santa Claus at her mother's department store.",
        comments: "A Christmas classic that will make anyone wish Santa were real. When I was a kid I always secretly admired that there's no dad in the story. Maureen O'Hara is a badass on her own and totally allowed to find love again.",
        inColor: false,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Miss Me This Christmas",
        myScore: 57,
        summary: "A couple signing their divorce papers on Christmas Eve starts to regret their split.",
        comments: "The 'nice' rich guy she goes on a date with is such a creep that I actually had to skip their date. BUT, the best friend is bi and into all kinds of things, so that's nice",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "My Christmas Inn",
        myScore: 80,
        summary: "A successful young woman travels to a small town in Alaska to flip the inn that belonged to her maiden great aunt.",
        comments: "Tia Mowry is relatable and likable AF.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: true,
        deadParent: true,
        famousActor: false,
        childActor: true,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "Operation Christmas Drop",
        myScore: 60,
        summary: "A Congressional aide is sent to Guam to pull the plug on any overly expensive military activities in order to win her boss reelection.",
        comments: "This is straight military propaganda and imperialism. And that CGI gekko was more than I could take.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Pottersville",
        myScore: 66,
        summary: "A general store owner in a dying town revitalizes its tourism by posing as Bigfoot.",
        comments: "This has such a solid cast, but its energy is uneven, making it feels more 90s than it should.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true, 
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Santa Claus Conquers the Martians",
        myScore: 49,
        summary: "When a Martian father is disturbed by how much Earthling TV his children are watching, he kidnaps Santa Claus - and, inadvertently, two human children.",
        comments: "Santa in space! What could go wrong?",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Santa Claus vs. The Devil",
        myScore: 51,
        summary: "When a devil named Pitch tries to turn the children of Mexico naughty, Santa himself must intercede to keep their hearts pure.",
        comments: "This movie is unwatchable -- unless you watch the version with Mike and the bots.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Scrooge",
        myScore: 77,
        summary: "A rich old man learns the meaning of Christmas from four ghosts and their songs.",
        comments: "Tied for fourth, with an edge for the songs, but boring unless someone is singing. It's way too long, and it's got those stifled British pauses. BUT you can't beat 'Thank You Very Much.'",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: false,
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Scrooged",
        myScore: 81,
        summary: "A rich old man who lives in New York City at a TV station in the 80s learns the meaning of Christmas from four ghosts.",
        comments: "The second-best one. Who knew you needed the Solid Gold Dancers in A Christmas Carol?",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "Sense, Sensibility, and Snowmen",
        myScore: 72,
        summary: "Two sisters go into business together, but the older isn't sure that the younger has what it takes to stick with a project. Plus, it's Christmas.",
        comments: "Somewhat disappointed that Eleanor, not Marianne, is more of the focus, but I guess she's the 'fun' one. On the other hand, she's pretty relatable. I don't totally understand why she and Edward are so crazy about each other though. Also, I'm really tired of actors expressing every emotion by opening their mouths.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: true,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Snowbound for Christmas",
        myScore: 62,
        summary: "A graphic designer finds herself trapped at an empty luxury inn with her hot new boss over Christmas.",
        comments: "A total lack of chemistry between the two leads. WAY too many long conversation scenes. And then they still work together AND display PDA in their office of only TWELVE PEOPLE? It's an HR disaster waiting to happen.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Star Wars Holiday Special",
        myScore: 41,
        summary: "Chewie and Han run into trouble as they head back to Kashyyyk for Life Day.",
        comments: "An absolute mess of an idea. Not even nostalgia, Boba Fett, and Bea Arthur can save this one.",
        inColor: true,
        romance: false,
        musical: true,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "The Christmas Chronicles: Part Two",
        myScore: 75,
        summary: "A young girl runs away from home to the North Pole, where a disgruntled former elf is trying to take down Santa Claus.",
        comments: "Kurt Russell makes a great Santa, but I could do without a 10-minute ooh-and-ahh tour of the North Pole. And the song and dance number. And the protagonist borderline flirting with her dead 13-year-old father. And the weirdly long and slow rendition of O Christmas Tree. Lots of telling AND showing, re: Mrs. Claus's potion abilities. I was pleased to see Julian Dennison get some more screen time, though.",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Family Stone",
        myScore: 67,
        summary: "A snooty Manhattanite travels to the boonies to meet her fiance's large, judgemental family on Christmas.",
        comments: "This movie was so disappointing. Such a great cast, but the trailer shows the only parts that aren't boring. The logic of the story doesn't make any sense, and using cancer to make us feel something at the end is a dirty trick that only makes us feel angry that the movie wasn't better.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: true,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: true,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "The Holiday",
        myScore: 42,
        summary: "An L.A. businesswoman and an English cottage owner swap homes to rediscover themselves.",
        comments: "Jack Black is the best part and he's way underused. The only movie I've ever hit my head against the wall while watching.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: true,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: true,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "The Holiday Calendar",
        myScore: 80,
        summary: "A young woman finds more than chocolates when a magical advent calendar predicts events in her life.",
        comments: "I liked the concept but I couldn't get over the lead actor's uneven face.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Knight Before Christmas",
        myScore: 47,
        summary: "A knight is sent to the future by a magical hag, where he meets a young woman who doesn't have time for Christmas.",
        comments: "I don't know what I expected.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: true,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: false,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Muppet Christmas Carol",
        myScore: 100,
        summary: "A rich old man learns the meaning of Christmas from the Muppets.",
        comments: "Funny, delightful, AND scary? Also, Michael Caine and Gonzo. This movie truly has it all.",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Nightmare Before Christmas",
        myScore: 85,
        summary: "The king of Halloween discovers Christmas exists and kidnaps Santa to make his own town more jolly.",
        comments: "A classic for two holidays",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Princess Switch",
        myScore: 40,
        summary: "A duchess and a baker discover they are identical distant relatives, and switch places so the duchess can experience normal life before her arranged marriage.",
        comments: "I don't know what I expected",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true,
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: true,
        deadParent: false,
        famousActor: false,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Princess Switch 2: Switched Again",
        myScore: 43,
        summary: "Long-long twin cousins switch places to fix their relationships, but a third twin cousin throws a wrench into the plans when she kidnaps one of them and takes their place.",
        comments: "I DON'T UNDERSTAND HOW AMBER AND HER CHRISTMAS PRINCE EXIST IN THIS WORLD WHEN THE DUCHESS CLEARLY WATCHED THE CHRISTMAS PRINCE WITH THE BAKER IN THE FIRST MOVIE.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: true,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: true,
        deadParent: false,
        famousActor: false,
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "The Santa Clause",
        myScore: 71,
        summary: "After accidentally killing Santa, a divorced dad is forced to take up the mantle.",
        comments: "I remember being super annoyed by the clearly Jewish 'punk' elf - more because he's punk and trying to cash in on the Rufio look. The fact that he's Jewish is hilarious",
        inColor: true,
        romance: false,
        musical: false,
        mistakenIdentity: false, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: true,
        adaptation: false,
        freshStart: false,
        precociousChild: true,
        charmingBaker: false,
        deadParent: false,
        famousActor: true, 
        childActor: true,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "Trading Places",
        myScore: 79,
        summary: "Two manipulative brothers switch the lives of a stock broker and a con mon in the hopes of winning a bet about nature vs. nuture.",
        comments: "There is certainly some unnecessary toplessness, but it was the 80s.",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: true,
        childActor: false,
        familyFriendly: false,
        pilf: false
    },
    {
        title: "While You Were Sleeping",
        myScore: 74,
        summary: "A lonely young woman finds herself in the middle of a raucous, loving family when she accidentally tricks them into believing that she's engaged to their comatose son.",
        comments: "A rare entry as Christmas Day happens at the inciting incident, instead of the climax. And I certainly don't always cry at the end. You cry at the end",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: true, 
        charmingInn: false,
        royalFairyTale: false,
        familyIsNumber1: true,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: true,
        famousActor: true,
        childActor: false,
        familyFriendly: true,
        pilf: false
    },
    {
        title: "White Christmas",
        myScore: 86,
        summary: "Two successful song-and-dance men help their former commanding officer bring business to his struggling Connecticut inn.",
        comments: "Another minstrel routine...oops. At least they didn't do black face for this one. I'm sure you don't tear up at the end when the general sees all his men because WHO WOULD DO THAT",
        inColor: true,
        romance: true,
        musical: true,
        mistakenIdentity: false,
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: false,
        wishFulfillment: false,
        realSanta: false,
        adaptation: true, 
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: true
    },
    {
        title: "You Can't Fight Christmas",
        myScore: 71,
        summary: "A hotel owner clases with his Christmas-loving decoroator.",
        comments: "I almost had a heart attack when I realized that this movie and Miss Me This Christmas exist in the same universe and happen simulataneously. What a choice",
        inColor: true,
        romance: true,
        musical: false,
        mistakenIdentity: false,
        charmingInn: true,
        royalFairyTale: false,
        familyIsNumber1: false,
        countryVsCity: false,
        corporateLemming: true,
        wishFulfillment: false,
        realSanta: false,
        adaptation: false,
        freshStart: false,
        precociousChild: false,
        charmingBaker: false,
        deadParent: false,
        famousActor: false,
        childActor: false,
        familyFriendly: true,
        pilf: false
    }
]

    /*  title:
        myScore:
        summary:
        comments: 
        inColor: 
        romance: 
        musical: 
        mistakenIdentity: 
        charmingInn: 
        royalFairyTale: 
        familyIsNumber1: 
        countryVsCity: 
        corporateLemming: 
        wishFulfillment: 
        realSanta: 
        adaptation: 
        freshStart: 
        precociousChild: 
        charmingBaker: 
        deadParent: 
        famousActor: 
        childActor: 
        familyFriendly:
        pilf:
        */

